### ISSUE TITLE
If nothing to update, do not send email

### ISSUE THREAD

**Issue by mnicolas80** [padosoft/laravel-composer-security#2]
Hi!

It would be nice to "disable" email notifications, when the package does not find updates.
In details, I am using your example that sends email notifications:

```
$schedule->command('composer-security:check "/dir/to/check/" --mail=mymail@mydomain')
            ->daily()
            ->withoutOverlapping()
            ->sendOutputTo(Config::get('composer-security-check.logFilePath'));
```

It would be interesting, to add a flag that forces the package to not send emails, when no update is found. In this case, the schedule will not "annoy" us if nothing needs to happen.
maybe something like:

```
$schedule->command('composer-security:check "/dir/to/check/" --mail=mymail@mydomain --always')
```

if no '--always' flag provided, the package will not send emails when no updates found,

Thank you,
Nikolaos

**Comment by lopadova** [comment]
It was decided to use this default behavior, because I prefer to receive email notification in all cases. Then in my inbox, I create a tag / filter ..
I prefer to use this strategy, so I realize that everything works (even the daily scheduler) because not having in the company a centralized system log.
But I understand that you can not be agree with this strategy and thus add a specific flag can accommodate both.
